---
# defaultRules:
#   rules:
#     etcd: false
#     kubeScheduler: false
# kubeControllerManager:
#   enabled: false
# kubeEtcd:
#   enabled: false
# kubeScheduler:
#   enabled: false
prometheus:
  service:
    annotations: {}
    labels: {}
    type: LoadBalancer
    port: 9090
    targetPort: 9090
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: prod-monitoring
commonLabels:
  prometheus: prod-monitoring

grafana:
  service:
    enabled: true
    type: LoadBalancer
    port: 80
    targetPort: 3000
      # targetPort: 4181 To be used with a proxy extraContainer
    ## Service annotations. Can be templated.
    annotations: {}
    labels: {}
    portName: service
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []

